#############################################################################
# Makefile for building: LectorAlmacenDeDatos
# Generated by qmake (2.01a) (Qt 4.8.7) on: mié oct 19 17:25:33 2016
# Project:  LectorAlmacenDeDatos.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile LectorAlmacenDeDatos.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -Iqmlapplicationviewer -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtDeclarative -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Utilidades/configuracionxml.cpp \
		Utilidades/database.cpp \
		moduloreclamos.cpp \
		modulotareas.cpp \
		moduloreportes.cpp \
		moduloperfilestiemporesolucion.cpp \
		moduloperfilestiemporesoluciondetalle.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc_qmlapplicationviewer.cpp \
		moc_moduloreclamos.cpp \
		moc_modulotareas.cpp \
		moc_moduloreportes.cpp \
		moc_moduloperfilestiemporesolucion.cpp \
		moc_moduloperfilestiemporesoluciondetalle.cpp \
		qrc_Fuente.cpp \
		qrc_Imagenes.cpp
OBJECTS       = main.o \
		configuracionxml.o \
		database.o \
		moduloreclamos.o \
		modulotareas.o \
		moduloreportes.o \
		moduloperfilestiemporesolucion.o \
		moduloperfilestiemporesoluciondetalle.o \
		qmlapplicationviewer.o \
		moc_qmlapplicationviewer.o \
		moc_moduloreclamos.o \
		moc_modulotareas.o \
		moc_moduloreportes.o \
		moc_moduloperfilestiemporesolucion.o \
		moc_moduloperfilestiemporesoluciondetalle.o \
		qrc_Fuente.o \
		qrc_Imagenes.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		LectorAlmacenDeDatos.pro
QMAKE_TARGET  = LectorAlmacenDeDatos
DESTDIR       = 
TARGET        = LectorAlmacenDeDatos

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LectorAlmacenDeDatos.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtDeclarative.prl \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile LectorAlmacenDeDatos.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtDeclarative.prl:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile LectorAlmacenDeDatos.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/LectorAlmacenDeDatos1.0.0 || $(MKDIR) .tmp/LectorAlmacenDeDatos1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/LectorAlmacenDeDatos1.0.0/ && $(COPY_FILE) --parents qmlapplicationviewer/qmlapplicationviewer.h Utilidades/configuracionxml.h Utilidades/database.h moduloreclamos.h modulotareas.h moduloreportes.h moduloperfilestiemporesolucion.h moduloperfilestiemporesoluciondetalle.h .tmp/LectorAlmacenDeDatos1.0.0/ && $(COPY_FILE) --parents Fuente.qrc Imagenes.qrc .tmp/LectorAlmacenDeDatos1.0.0/ && $(COPY_FILE) --parents main.cpp Utilidades/configuracionxml.cpp Utilidades/database.cpp moduloreclamos.cpp modulotareas.cpp moduloreportes.cpp moduloperfilestiemporesolucion.cpp moduloperfilestiemporesoluciondetalle.cpp qmlapplicationviewer/qmlapplicationviewer.cpp .tmp/LectorAlmacenDeDatos1.0.0/ && (cd `dirname .tmp/LectorAlmacenDeDatos1.0.0` && $(TAR) LectorAlmacenDeDatos1.0.0.tar LectorAlmacenDeDatos1.0.0 && $(COMPRESS) LectorAlmacenDeDatos1.0.0.tar) && $(MOVE) `dirname .tmp/LectorAlmacenDeDatos1.0.0`/LectorAlmacenDeDatos1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/LectorAlmacenDeDatos1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qmlapplicationviewer.cpp moc_moduloreclamos.cpp moc_modulotareas.cpp moc_moduloreportes.cpp moc_moduloperfilestiemporesolucion.cpp moc_moduloperfilestiemporesoluciondetalle.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qmlapplicationviewer.cpp moc_moduloreclamos.cpp moc_modulotareas.cpp moc_moduloreportes.cpp moc_moduloperfilestiemporesolucion.cpp moc_moduloperfilestiemporesoluciondetalle.cpp
moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

moc_moduloreclamos.cpp: moduloreclamos.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduloreclamos.h -o moc_moduloreclamos.cpp

moc_modulotareas.cpp: modulotareas.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) modulotareas.h -o moc_modulotareas.cpp

moc_moduloreportes.cpp: moduloreportes.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduloreportes.h -o moc_moduloreportes.cpp

moc_moduloperfilestiemporesolucion.cpp: moduloperfilestiemporesolucion.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduloperfilestiemporesolucion.h -o moc_moduloperfilestiemporesolucion.cpp

moc_moduloperfilestiemporesoluciondetalle.cpp: moduloperfilestiemporesoluciondetalle.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduloperfilestiemporesoluciondetalle.h -o moc_moduloperfilestiemporesoluciondetalle.cpp

compiler_rcc_make_all: qrc_Fuente.cpp qrc_Imagenes.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Fuente.cpp qrc_Imagenes.cpp
qrc_Fuente.cpp: Fuente.qrc \
		qml/LectorAlmacenDeDatos/main.qml \
		qml/LectorAlmacenDeDatos/BarraInferior.qml \
		qml/LectorAlmacenDeDatos/PreviewReporte.qml \
		qml/LectorAlmacenDeDatos/ConsultasSql.js \
		qml/LectorAlmacenDeDatos/PreviewReclamo.qml \
		qml/LectorAlmacenDeDatos/ConfiguracionTiempoResolucion.qml \
		qml/LectorAlmacenDeDatos/Controles/CheckBox.qml \
		qml/LectorAlmacenDeDatos/Controles/BotonBarraDeHerramientas.qml \
		qml/LectorAlmacenDeDatos/Controles/BotonSimple.qml \
		qml/LectorAlmacenDeDatos/Controles/BotonIns.qml \
		qml/LectorAlmacenDeDatos/Controles/BotonFlecha.qml \
		qml/LectorAlmacenDeDatos/Controles/ComboBoxCheckBox.qml \
		qml/LectorAlmacenDeDatos/Delegados/Delegate_ListaTareas.qml \
		qml/LectorAlmacenDeDatos/Delegados/Delegate_ListaReclamosControl.qml \
		qml/LectorAlmacenDeDatos/Delegados/Delegate_ListaReclamos.qml \
		qml/LectorAlmacenDeDatos/Delegados/Delegate_ListaItemsConfiguracionTiempoResolucion.qml \
		qml/LectorAlmacenDeDatos/Delegados/Delegate_ListaItemsSeleccionados.qml
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name Fuente Fuente.qrc -o qrc_Fuente.cpp

qrc_Imagenes.cpp: Imagenes.qrc \
		qml/LectorAlmacenDeDatos/Imagenes/arrow_down.png \
		qml/LectorAlmacenDeDatos/Imagenes/VistoOk.png \
		qml/LectorAlmacenDeDatos/Imagenes/CerrarLista.png \
		qml/LectorAlmacenDeDatos/Imagenes/Maximizar.png \
		qml/LectorAlmacenDeDatos/Imagenes/FlechaDerecha.png \
		qml/LectorAlmacenDeDatos/Imagenes/FlechaAbajo.png \
		qml/LectorAlmacenDeDatos/Imagenes/icono.png \
		qml/LectorAlmacenDeDatos/Imagenes/arrow_up.png \
		qml/LectorAlmacenDeDatos/Imagenes/Fondo.png \
		qml/LectorAlmacenDeDatos/Imagenes/FlechaIzquierda.png \
		qml/LectorAlmacenDeDatos/Imagenes/Restaurar.png \
		qml/LectorAlmacenDeDatos/Imagenes/FlechaArriba.png \
		qml/LectorAlmacenDeDatos/Imagenes/FlechaAbajo16x16.png \
		qml/LectorAlmacenDeDatos/Imagenes/FlechaArriba16x16.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name Imagenes Imagenes.qrc -o qrc_Imagenes.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp moduloreclamos.h \
		modulotareas.h \
		Utilidades/configuracionxml.h \
		moduloreportes.h \
		moduloperfilestiemporesolucion.h \
		Utilidades/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

configuracionxml.o: Utilidades/configuracionxml.cpp Utilidades/configuracionxml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configuracionxml.o Utilidades/configuracionxml.cpp

database.o: Utilidades/database.cpp Utilidades/database.h \
		Utilidades/configuracionxml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o Utilidades/database.cpp

moduloreclamos.o: moduloreclamos.cpp moduloreclamos.h \
		Utilidades/database.h \
		Utilidades/configuracionxml.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moduloreclamos.o moduloreclamos.cpp

modulotareas.o: modulotareas.cpp modulotareas.h \
		Utilidades/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modulotareas.o modulotareas.cpp

moduloreportes.o: moduloreportes.cpp moduloreportes.h \
		Utilidades/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moduloreportes.o moduloreportes.cpp

moduloperfilestiemporesolucion.o: moduloperfilestiemporesolucion.cpp moduloperfilestiemporesolucion.h \
		Utilidades/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moduloperfilestiemporesolucion.o moduloperfilestiemporesolucion.cpp

moduloperfilestiemporesoluciondetalle.o: moduloperfilestiemporesoluciondetalle.cpp moduloperfilestiemporesoluciondetalle.h \
		Utilidades/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moduloperfilestiemporesoluciondetalle.o moduloperfilestiemporesoluciondetalle.cpp

qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

moc_moduloreclamos.o: moc_moduloreclamos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moduloreclamos.o moc_moduloreclamos.cpp

moc_modulotareas.o: moc_modulotareas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modulotareas.o moc_modulotareas.cpp

moc_moduloreportes.o: moc_moduloreportes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moduloreportes.o moc_moduloreportes.cpp

moc_moduloperfilestiemporesolucion.o: moc_moduloperfilestiemporesolucion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moduloperfilestiemporesolucion.o moc_moduloperfilestiemporesolucion.cpp

moc_moduloperfilestiemporesoluciondetalle.o: moc_moduloperfilestiemporesoluciondetalle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moduloperfilestiemporesoluciondetalle.o moc_moduloperfilestiemporesoluciondetalle.cpp

qrc_Fuente.o: qrc_Fuente.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Fuente.o qrc_Fuente.cpp

qrc_Imagenes.o: qrc_Imagenes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Imagenes.o qrc_Imagenes.cpp

####### Install

install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/qml/ 
	-$(INSTALL_DIR) /home/cristian/qtProyectos/LectorAlmacenDeDatos/qml/LectorAlmacenDeDatos $(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/qml/LectorAlmacenDeDatos
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/qml/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/LectorAlmacenDeDatos/bin/ 


install:  install_itemfolder_01 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_target   FORCE

FORCE:

